[package]
name = "yinsh"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.14.0" }
rand = "0.8.5"
bevy_tweening = { git = "https://github.com/BraymatterOrg/bevy_tweening_0_14", branch = "0.14" }
serde_yaml = "0.9.34"
serde = "1.0.204"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
lto = "thin"

[profile.wasm-release]
inherits = "release"
opt-level = "z"
strip = "debuginfo"
