[package]
name = "yinsh_nn"
version = "0.1.0"
authors = ["David Peter <mail@david-peter.de>"]
description = "Neural network heuristic for Yinsh AI."
homepage = "https://david-peter.de/yinsh"
repository = "https://github.com/sharkdp/yinsh"
license = "MIT OR Apache-2.0"
edition = "2024"

[dependencies]
yinsh = { path = "../yinsh" }
yinsh_ai = { path = "../yinsh_ai" }
runnt = "0.9"
minimax = "0.5.3"
tracing = "0.1"
