[package]
name = "yinsh"
version = "0.1.0"
authors = ["David Peter <mail@david-peter.de>"]
description = "Core game logic for the abstract board game Yinsh."
homepage = "https://david-peter.de/yinsh"
repository = "https://github.com/sharkdp/yinsh"
license = "MIT OR Apache-2.0"
edition = "2024"

[dependencies]
itertools = "0.14.0"
serde = { version = "1.0.204", features = ["derive"] }
serde_yaml = "0.9.34"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "board"
harness = false
