[package]
name = "yinsh_gui"
version = "0.1.0"
authors = ["David Peter <mail@david-peter.de>"]
description = "Bevy-based GUI for the abstract board game Yinsh."
homepage = "https://david-peter.de/yinsh"
repository = "https://github.com/sharkdp/yinsh"
license = "MIT OR Apache-2.0"
edition = "2024"

[dependencies]
yinsh = { path = "../yinsh" }
yinsh_ai = { path = "../yinsh_ai" }

bevy = { version = "0.17" }
bevy_tweening = "0.14"
bevy_async_task = "0.11"

tracing = "0.1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
gloo-timers = { version = "0.3", features = ["futures"] }

[[bin]]
name = "yinsh"
path = "src/main.rs"
